### ISSUE TITLE
Bug: Trajectorylet streamer does not handle more than 1 object

### ISSUE THREAD

**Issue by victorjarlow** [RI-SE/ATOS#459]
steps to reproduce: 
Run ATOS with more than 2 objects,
Init -> connect. 
On connect there is a segmentation fault on line 32 in trajectorypublisher.cpp (pub.publish(trajMsg); )

**Comment by victorjarlow** [comment]
@samuelthoren can this be closed?

**Comment by samuelthoren** [comment]
See https://github.com/RI-SE/ATOS/pull/603
