### ISSUE TITLE
ObjectControl does not use max_missing_heartbeats from conf

### ISSUE THREAD

**Issue by Angeleon** [RI-SE/ATOS#619]
**Describe the bug**
ObjectControl uses iso22133 default MONR_EXPECTED_FREQUENCY_HZ for communication instead of using max_missing_heartbeats and sending this value in the OSEM [Communication Timeout] value.

**Expected behavior**
If max_missing_heartbeats is set in the params.yaml file, it should overwrite the timeout values in the ObjectControl class and send this timeout in the OSEM message to the test objects.

**Branch or release information (please complete the following information):**
 - all

**Comment by Robert108** [comment]
Fixed in #621
